# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aad9335a81dc8dba99adf7f685bf4d5f"
name = "Inventory Sync Monitor"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,write_inventory,read_locations"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels_update"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products_update"
  topics = [ "products/update" ]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
